import React from 'react'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AI } from "@/api/stateManager/action";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function Template({ children, current, slant }:Readonly< { children: React.ReactNode, current: any, user: any, slant: React.ReactNode }>) {

  return (
    <>
      <div className="z-20">
        <div className="z-20">
          <Header/>
        <div className="bg-gradient-to-b from-white to-neutral-100 ">
          <div className="flex flex-col z-20">
          <div className="z-20 " >
            <AI>
            {children}
            </AI>
          </div>
          </div>
          </div>
        </div>
        <div className="z-10">
          {slant}
        </div>
      </div>
    </>
  )
}
